/**
 * pages/admin/routes.js - route table. Each page module has a default export
 * `async (ctx, mountEl) => void`. Modules are lazily imported on navigation.
 */
export const PAGE_ROUTES = [
  { path: '/', permission: 'dashboard.view', title: 'Dashboard', load: () => import('./dashboard.js') },
  { path: '/products', permission: 'products.view', title: 'Products', load: () => import('./products.js') },
  { path: '/products/new', permission: 'products.create', title: 'New Product', load: () => import('./product-form.js') },
  { path: '/products/:id', permission: 'products.view', title: 'Product', load: () => import('./product-detail.js') },
  { path: '/products/:id/edit', permission: 'products.edit', title: 'Edit Product', load: () => import('./product-form.js') },
  { path: '/categories', permission: 'products.view', title: 'Categories', load: () => import('./categories.js') },
  { path: '/brands', permission: 'products.view', title: 'Brands', load: () => import('./brands.js') },
  { path: '/barcodes', permission: 'barcode.manage', title: 'Barcode Generator', load: () => import('./barcode-generator.js') },
  { path: '/inventory', permission: 'inventory.view', title: 'Inventory', load: () => import('./inventory.js') },
  { path: '/stock-adjustments', permission: 'inventory.adjust', title: 'Stock Adjustments', load: () => import('./stock-adjustments.js') },
  { path: '/stock-transfers', permission: 'inventory.transfer', title: 'Stock Transfers', load: () => import('./stock-transfers.js') },
  { path: '/purchases', permission: 'purchases.view', title: 'Purchases', load: () => import('./purchases.js') },
  { path: '/purchases/new', permission: 'purchases.create', title: 'New Purchase', load: () => import('./purchase-form.js') },
  { path: '/purchases/:id/edit', permission: 'purchases.edit', title: 'Edit Purchase', load: () => import('./purchase-form.js') },
  { path: '/purchases/:id', permission: 'purchases.view', title: 'Purchase', load: () => import('./purchase-detail.js') },
  { path: '/purchase-returns', permission: 'purchases.return', title: 'Purchase Returns', load: () => import('./purchase-returns.js') },
  { path: '/suppliers', permission: 'purchases.view', title: 'Suppliers', load: () => import('./suppliers.js') },
  { path: '/sales', permission: 'sales.view', title: 'Sales', load: () => import('./sales.js') },
  { path: '/sales/:id', permission: 'sales.view', title: 'Sale', load: () => import('./sale-detail.js') },
  { path: '/sales-returns', permission: 'sales.view', title: 'Exchange / Return', load: () => import('./sales-returns.js') },
  { path: '/invoices', permission: 'sales.view', title: 'Invoices', load: () => import('./invoices.js') },
  { path: '/customers', permission: 'customers.view', title: 'Customers', load: () => import('./customers.js') },
  { path: '/employees', permission: 'employees.view', title: 'Employees', load: () => import('./employees.js') },
  { path: '/expenses', permission: 'expenses.view', title: 'Expenses', load: () => import('./expenses.js') },
  { path: '/cash-register', permission: 'register.view', title: 'Cash Register', load: () => import('./cash-register.js') },
  { path: '/discounts', permission: 'discounts.manage', title: 'Discounts', load: () => import('./discounts.js') },
  { path: '/taxes', permission: 'taxes.manage', title: 'Discount & VAT', load: () => import('./taxes.js') },
  { path: '/reports', permission: 'reports.view', title: 'Reports', load: () => import('./reports.js') },
  { path: '/reports/:type', permission: 'reports.view', title: 'Report', load: () => import('./reports.js') },
  { path: '/audit-logs', permission: 'audit.view', title: 'Audit Logs', load: () => import('./audit-logs.js') },
  { path: '/notifications', permission: 'notifications.view', title: 'Notifications', load: () => import('./notifications.js') },
  { path: '/branches', permission: 'branches.manage', title: 'Branches', load: () => import('./branches.js') },
  { path: '/billing', permission: 'settings.manage', title: 'Subscription & Billing', load: () => import('./billing.js') },
  { path: '/settings', permission: 'settings.manage', title: 'Settings', load: () => import('./settings.js') },
  { path: '/backup', permission: 'backup.manage', title: 'Backup / Data', load: () => import('./backup.js') },
  { path: '/help', permission: null, title: 'Help', load: () => import('./help.js') },
];
